name: Actualizar Boxeo Semanal ğŸ¥Š

on:
  schedule:
    - cron: '0 8 * * 0' # Domingos a las 8 AM
  workflow_dispatch: # BotÃ³n manual para probar AHORITA

jobs:
  boxeo-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar cÃ³digo ğŸ“¥
        uses: actions/checkout@v3

      - name: Instalar Python ğŸ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerÃ­as ğŸ“š
        run: |
          pip install -r requirements.txt

      - name: Correr Script ğŸƒâ€â™‚ï¸
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python main.py